### ISSUE TITLE
API 3.0.0-ALPHA12 Unsupported

### ISSUE THREAD

**Issue by Scali3n** [DaPigGuy/PiggyCrates#10]
hey dude , yes I use your 3 plugin x) and I love it! but the problem on this one is that when I configure the crate with CE, I reload and the ... the plugin just does not work anymore, it's a shame because I wanted to make a server especially on your extraordinary plugin :) , I hope you will help me, at the fact I followed the instructions to the letter :/ thank you

**Comment by Aericio** [comment]
Version of PMMP? /version

**Comment by DaPigGuy** [comment]
Are there any errors? Does the plugin load? Can you show your crates.yml?

**Comment by Scali3n** [comment]
i have the latest version of pocketmine, i get the error that i found, and my crate.yml file configuration, i tested with my config its not working so i reinstall the plugin and i I took the example that you had to give: / otherwise your plugin is just extra besides this little bug ^^ '

**Comment by Scali3n** [comment]
![screenshot_20180502-094855](https://user-images.githubusercontent.com/38808035/39511790-f65127a6-4dee-11e8-828a-2a71450a221b.png)
![screenshot_20180502-094551](https://user-images.githubusercontent.com/38808035/39511791-f6afc7c0-4dee-11e8-83f9-861e0b5ae866.png)
![screenshot_20180502-094520](https://user-images.githubusercontent.com/38808035/39511793-f6d9960e-4dee-11e8-9b5c-b67b5cddad02.png)
![screenshot_20180501-230112](https://user-images.githubusercontent.com/38808035/39511795-f713c7ac-4dee-11e8-87cc-bb9b2ca504b6.png)

**Comment by Aericio** [comment]
I'll work on updating the api sometime next week... busy with finals.

Other plugins seem to have the same issue of unsupported API also. You should find their github repositories and re-download the plugin if there was an API update for ALPHA12.

**Comment by Scali3n** [comment]
Thank you, you manage, his mark me may be the error of API except that the plugin works anyway so I do not understand ^^ 'good time that his walk I do not complain, the fact it does me the same for PyggyCustomEnchantShop, yet everything works but when I add a delight to sell it does not show it, you do a great job :) my server opens within 2 weeks so I hope that the 2 plugin will be set :3 i' love your plugin :)

**Comment by DaPigGuy** [comment]
You are not correctly formatting your crates.yml.
It should look something like this:
```
 weapons:
    drops:
      276:
        name: "Sword of Death"
        meta: 0
        amount: 1
        enchantments:
            Deathbringer:
                level: 5
      261:
        name: "Bow of Pig"
        meta: 0
        amount: 1
        enchantments:
            Porkified:
                level: 1
    amount: 1
    block: "133:0"
```
