### ISSUE TITLE
Support for PCEBookshop

### ISSUE THREAD

**Issue by JGYTVevo** [DaPigGuy/PiggyCrates#63]
Please make sure your issue complies with these guidelines:
- * [Winnable unopened books ]
- * [how you buy a book and get a random enchant, i would like to be able to get for example "mythic book" instead of a already enchanted book ] 

### Description

Be able to win "mythic" books that you can open like how you can buy them with PCEBookshop! Very good plugin overall!
### Extra Information

**Comment by Aericio** [comment]
This can already be done using NBT.

Given that PCEBookShop is installed, add `nbt: "{pcebookshop:#}"` and substitute # for the rarity. The number must be an integer value because that's how my plugin is setup to read the nbt data. 

Read [here](https://github.com/Aericio/PCEBookShop#quick-tip-for-players) for rarity integer values.

Example, which will give a book of mythic rarity.
```yaml
    drops:
      - id: 340
        meta: 0
        amount: 1
        chance: 64
        name: "ce book"
        lore: "its random click to chance"
        nbt: "{pcebookshop:1}"
```
