### ISSUE TITLE
Items with same ID

### ISSUE THREAD

**Issue by SpecialistNinja** [DaPigGuy/PiggyCrates#8]
Let say i put this in my crate.yml
```
common:
    drops:
      52:
        name: "Spawner IG"
        meta: 20
        amount: 1
      52:
        name: "Spawner Zombie"
        meta: 32
        amount: 1
    amount: 1
    block: "173:0"
```

I tried two stacks of keys, i always end up winning "Spawner IG" never win "Spawner Zombie"

Then...
When i put this in my crate.yml

```
common:
    drops:
      52:
        name: "Spawner IG"
        meta: 20
        amount: 1
      1:
        name: "Stone"
        meta: 0
        amount: 1
    amount: 1
    block: "173:0"
```

I tried two stacks of keys, now it work and end up winning both items

I believe the issue is caused by using the same ID tag twice, and the plugin ignores it.

-52:20
and
-52:32
doesn't work and the crate system only let you win one of it in every keys you try.
